/*
 * SEVSEG_Interfacing.c
 *
 * Created: 9/24/2022 2:26:00 AM
 *  Author: User
 */ 
#include "SEVSEG_Private.h"

void SEG_Initialzation(void)
{
	DIO_SETPIN_DIRECTION(SEVSEG_CNTRL_PRT,SEVSEG_EN1,DIO_OUTPUT);
	DIO_SETPIN_DIRECTION(SEVSEG_CNTRL_PRT,SEVSEG_EN2,DIO_OUTPUT);
	DIO_SETPIN_DIRECTION(SEVSEG_CNTRL_PRT,SEVSEG_DIP,DIO_OUTPUT);
	
	DIO_SETPIN_DIRECTION(SEVSEG_CNTRL_PRT,SEVSEG_A,DIO_OUTPUT);
	DIO_SETPIN_DIRECTION(SEVSEG_CNTRL_PRT,SEVSEG_B,DIO_OUTPUT);
	DIO_SETPIN_DIRECTION(SEVSEG_CNTRL_PRT,SEVSEG_C,DIO_OUTPUT);
	DIO_SETPIN_DIRECTION(SEVSEG_CNTRL_PRT,SEVSEG_D,DIO_OUTPUT);

}
void SEG_ENABLE1(void)
{
	DIO_SETPIN_VALUE(SEVSEG_CNTRL_PRT,SEVSEG_EN1,DIO_HIGH);
}
void SEG_ENABLE2(void)
{
	DIO_SETPIN_VALUE(SEVSEG_CNTRL_PRT,SEVSEG_EN2,DIO_HIGH);

}
void SEG_DISABLE1(void)
{
		DIO_SETPIN_VALUE(SEVSEG_CNTRL_PRT,SEVSEG_EN1,DIO_LOW);

}
void SEG_DISABLE2(void)
{
		DIO_SETPIN_VALUE(SEVSEG_CNTRL_PRT,SEVSEG_EN2,DIO_LOW);

}
void SEG_ENABLE_DIB(void)
{
		DIO_SETPIN_VALUE(SEVSEG_CNTRL_PRT,SEVSEG_DIP,DIO_HIGH);

}
void SEG_DISABLE_DIB(void)
{
		DIO_SETPIN_VALUE(SEVSEG_CNTRL_PRT,SEVSEG_DIP,DIO_LOW);

}

void SEG_DISPALY(uint16_t num)
{
	
	PORTA = num<<4 ;
	SEG_ENABLE1();
	SEG_DISABLE2();
	PORTA = num<<4 ;
	SEG_ENABLE2();
	SEG_DISABLE1();

}